export const products = [
  {
    id: 1,
    slug: "doritos-ruffles-degis-tokus",
    category: "atistirmalik",
    subcategory: "Cips",
    name: "Doritos & Ruffles Değiş Tokuş",
    price: 102.99,
    oldPrice: 113.98,
    quantity: "2 Ürün",
    image:
      "https://cdn-image.getir.com/market/product/ea0d34a8-7e6c-4c5d-a447-9f29e91e8e5d.jpg",
  },
  {
    id: 2,
    slug: "lays-ruffles-doritos-paketi",
    category: "atistirmalik",
    subcategory: "Cips",
    name: "Lay's Ruffles Doritos Paketi",
    price: 158.5,
    oldPrice: 175.99,
    quantity: "3 Ürün",
    image:
      "https://cdn-image.getir.com/market/product/bb557ed5-ff1d-45ae-b635-fff68381b3f7.jpg",
  },
  {
    id: 3,
    slug: "cerezza-uclusu",
    category: "atistirmalik",
    subcategory: "Cips",
    name: "Çerezza Üçlüsü",
    price: 100.5,
    oldPrice: 111.48,
    quantity: "3 Ürün",
    image:
      "https://cdn-image.getir.com/market/product/3fce5b10-10aa-4ca4-ae14-89f9e4c0281d.jpg",
  },
  {
    id: 4,
    slug: "pin-gong-ikilisi",
    category: "atistirmalik",
    subcategory: "Cips",
    name: "Pin & Gong İkilisi",
    price: 56.49,
    oldPrice: 50.5,
    quantity: "2 Ürün",
    image:
      "https://cdn-image.getir.com/market/product/7858ba71-e628-44b5-b870-bef46706e59b.png",
  },
  {
    id: 5,
    slug: "cheetos-firindan-peynir-misir-1",
    category: "atistirmalik",
    subcategory: "Cips",
    name: "Cheetos Fırından Peynir Mısır Çerezi Aile Boy",
    price: 56.97,
    oldPrice: 51.5,
    quantity: "3x40g",
    image:
      "https://cdn-image.getir.com/market/product/9ff2a1ac-fc28-4368-bd87-f945b4727af3.png",
  },
  {
    id: 6,
    slug: "ruffles-originals-patates-cipsi-super-boy",
    category: "atistirmalik",
    subcategory: "Cips",
    name: "Ruffles Originals Patates Cipsi Süper Boy",
    price: 46.99,
    oldPrice: 51.5,
    quantity: "107 g",
    image:
      "https://cdn-image.getir.com/market/product/b3a49501-8d15-4a95-a450-67edd9b7b1de.jpg",
    details: [
      "Ruffles Originals, atıştırmalık olarak tüketebileceğiniz bir patates cipsidir.",
      "Her anın tadını çıkarırken enfes cips Ruffles Originals'ı tercih edebilirsiniz.",
    ],
    ingredients: "Patates, palm olein yağı, tuz.",
    usage:
      "Serin ve kuru ortamda muhafaza ediniz. Doğrudan güneş ışığına maruz bırakmayınız.",
    additionalInfo:
      "Ürünün menşeine, üretici/ithalatçı bilgilerine ve uyarılara ulaşabilirsiniz. Menşei: Türkiye. Gıda İşletmecisi / Üretici / İthalatçı / Dağıtıcı: Frito Lay Gıda San. ve Tic. A.Ş. İşletme Kayıt No: TR-33-K-000513",
  },
  {
    id: 7,
    slug: "cheetos-firindan-peynir-misir-3",
    category: "atistirmalik",
    subcategory: "Cips",
    name: "Cheetos Fırından Peynir Mısır Çerezi Aile Boy",
    price: 56.97,
    oldPrice: 51.5,
    quantity: "3x40g",
    image:
      "https://cdn-image.getir.com/market/product/9ff2a1ac-fc28-4368-bd87-f945b4727af3.png",
  },
  {
    id: 8,
    slug: "cheetos-firindan-peynir-misir-4",
    category: "atistirmalik",
    subcategory: "Cips",
    name: "Cheetos Fırından Peynir Mısır Çerezi Aile Boy",
    price: 56.97,
    oldPrice: 51.5,
    quantity: "3x40g",
    image:
      "https://cdn-image.getir.com/market/product/9ff2a1ac-fc28-4368-bd87-f945b4727af3.png",
  },
  {
    id: 9,
    slug: "cheetos-firindan-peynir-misir-5",
    category: "atistirmalik",
    subcategory: "Cips",
    name: "Cheetos Fırından Peynir Mısır Çerezi Aile Boy",
    price: 56.97,
    oldPrice: 51.5,
    quantity: "3x40g",
    image:
      "https://cdn-image.getir.com/market/product/9ff2a1ac-fc28-4368-bd87-f945b4727af3.png",
  },
  {
    id: 10,
    slug: "cheetos-firindan-peynir-misir-6",
    category: "atistirmalik",
    subcategory: "Cips",
    name: "Cheetos Fırından Peynir Mısır Çerezi Aile Boy",
    price: 56.97,
    oldPrice: 51.5,
    quantity: "3x40g",
    image:
      "https://cdn-image.getir.com/market/product/9ff2a1ac-fc28-4368-bd87-f945b4727af3.png",
  },
  {
    id: 11,
    slug: "cheetos-firindan-peynir-misir-7",
    category: "atistirmalik",
    subcategory: "Cips",
    name: "Cheetos Fırından Peynir Mısır Çerezi Aile Boy",
    price: 56.97,
    oldPrice: 51.5,
    quantity: "3x40g",
    image:
      "https://cdn-image.getir.com/market/product/9ff2a1ac-fc28-4368-bd87-f945b4727af3.png",
  },
];
